version: '2'
services:
  db:
    build: ./postgresdb
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=notes_development
    volumes:
       - postgres-db-volume:/var/lib/postgresql/data
  notesapp:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
volumes:
  postgres-db-volume:
